; /etc/asterisk/pjsip.conf — TechLife VoiceBridge Enterprise
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1001]
type=endpoint
context=techlife-inbound
disallow=all
allow=ulaw,alaw,g722
aors=1001
auth=auth1001
direct_media=no
rtp_symmetric=yes
set_var=TECHLIFE_TENANT=TENANT_ID_HERE

[auth1001]
type=auth
auth_type=userpass
username=1001
password=agent1234

[1001]
type=aor
max_contacts=2

[1002]
type=endpoint
context=techlife-inbound
disallow=all
allow=ulaw,alaw,g722
aors=1002
auth=auth1002
direct_media=no
set_var=TECHLIFE_TENANT=TENANT_ID_HERE

[auth1002]
type=auth
auth_type=userpass
username=1002
password=agent1234

[1002]
type=aor
max_contacts=2

[1003]
type=endpoint
context=techlife-inbound
disallow=all
allow=ulaw,alaw,g722
aors=1003
auth=auth1003
direct_media=no
set_var=TECHLIFE_TENANT=TENANT_ID_HERE

[auth1003]
type=auth
auth_type=userpass
username=1003
password=agent1234

[1003]
type=aor
max_contacts=2
